
from django.contrib import admin
from django.urls import path,include
from .views import *
app_name='gestionstock'
urlpatterns = [

    path('', home,name='home'),
    path('facture', facture,name='facture'),
    path('chargerappro', chargerappro,name='chargerappro'),
    path('periode', periode,name='periode'),
    path('travaux', travaux,name='travaux'),
    path('listappro', listappro,name='listappro'),
    path('miseprixtempo', miseprixtempo,name='miseprixtempo'),
    path('getqteproduitfacture', getqteproduitfacture,name='getqteproduitfacture'),
    path('boncommande', boncommande,name='boncommande'),
    path('rapbonlivraison', rapbonlivraison,name='rapbonlivraison'),
    path('boncommandevalide', boncommandevalide,name='boncommandevalide'),
    path('boncommandeinterne', boncommandeinterne,name='boncommandeinterne'),
    path('transfert', transfert,name='transfert'),
    path('rapvariation', rapvariation,name='rapvariation'),
    path('retour', retour,name='retour'),
    path('delaiinventaire', delaiinventaire,name='delaiinventaire'),
    path('rapportlogiquephysique', rapportlogiquephysique,name='rapportlogiquephysique'),
    path('misestockinventaire', misestockinventaire,name='misestockinventaire'),
    path('inventaire', inventaire,name='inventaire'),
    path('rapmvtproduit', rapmvtproduit,name='rapmvtproduit'),
    path('rapinventairethéorique', rapinventairethéorique,name='rapinventairethéorique'),
    path('rapinventairethéoriqueval', rapinventairethéoriqueval,name='rapinventairethéoriqueval'),
    path('rapstock', rapstock,name='rapstock'),
    path('entrestockrecettes', entrestockrecettes,name='entrestockrecettes'),
    path('boncommandevalidesup', boncommandevalidesup,name='boncommandevalidesup'),
    path('rapclient', rapclient,name='rapclient'),
    path('rapsortie', rapsortie,name='rapsortie'),
    path('rapsortiefull', rapsortiefull,name='rapsortiefull'),
    path('rapachat', rapachat,name='rapachat'),
    path('visualisation', supprimer,name='visualisation'),
    path('supprimer', ajustement,name='supprimer'),
    path('getlistlivraison', getlistlivraison,name='getlistlivraison'),
    path('cloturecommande', cloturecommande,name='cloturecommande'),
    path('cloturecommande2', cloturecommande2,name='cloturecommande2'),
    path('supprimerretour', supprimerretour,name='supprimerretour'),
    path('validerlivraison', validerlivraison,name='validerlivraison'),
    path('getajustementpro', getajustementpro,name='getajustementpro'),
    path('ajustementpro', ajustementpro,name='ajustementpro'),
    path('ajustementqte', ajustementqte,name='ajustementqte'),
    path('ajustementqtesupprimer', ajustementqtesupprimer,name='ajustementqtesupprimer'),
    path('getsupprimer', getsupprimer,name='getsupprimer'),
    path('raprecette', raprecette,name='raprecette'),
    path('rapfournisseur', rapfournisseur,name='rapfournisseur'),
    path('getbon', getbon,name='getbon'),
    path('getrecettes', getrecettes,name='getrecettes'),
    path('getrecettesdetail', getrecettesdetail,name='getrecettesdetail'),
    path('fichetechnique', fichetechnique,name='fichetechnique'),
    path('plat', plat,name='plat'),
    path('getproduitinventaire', getproduitinventaire,name='getproduitinventaire'),
    path('entrestock', entrestock,name='entrestock'),
    path('entrestock2', entrestock2,name='entrestock2'),
    path('getboncommande', getboncommande,name='getboncommande'),
    path('boncommandevalidemodi', boncommandevalidemodi,name='boncommandevalidemodi'),
    path('getdetailboncommande', getdetailboncommande,name='getdetailboncommande'),
    path('deletearticle', deletearticle,name='deletearticle'),
    path('annulercommande', annulercommande,name='annulercommande'),
    path('getfacture', getfacture,name='getfacture'),
    path('getrecettes2', getrecettes2,name='getrecettes2'),
    path('getfacture2', getfacture2,name='getfacture2'),
    path('getfacture3', getfacture3,name='getfacture3'),
    path('getproduit', getproduit,name='getproduit'),
    path('getrecettesdetail2', getrecettesdetail2,name='getrecettesdetail2'),
    path('sortistockrecettes', sortistockrecettes,name='sortistockrecettes'),
    path('getrecettesdetailstock', getrecettesdetailstock,name='getrecettesdetailstock'),
    path('getrecettesdetailstocksorti', getrecettesdetailstocksorti,name='getrecettesdetailstocksorti'),

    path('check', check, name="check"),

    # path('rapportentreecmp', rapportentreecmp, name="rapportentreecmp"),
    # path('rapportsortiecmp', rapportsortiecmp, name="rapportsortiecmp"),
    # path('inventairecmp', inventairecmp, name="inventairecmp"),
    # path('situation', home, name="situation"),

    path('fichiers', fichiers, name="fichiers"),
    path('getlibemballage', getlibemballage, name="getlibemballage"),
    path('rapboncommande', rapboncommande, name="rapboncommande"),
    path('entrestockvalid', entrestockvalid, name="entrestockvalid"),
    path('modifyqte', modifyqte, name="modifyqte"),
    path('saisirphysique', saisirphysique, name="saisirphysique"),
    path('modiproduit', modiproduit, name="modiproduit"),
    path('production', production, name="production"),
    path('fabproduction', fabproduction, name="fabproduction"),
    path('deleteproduction', deleteproduction, name="deleteproduction"),
    path('getrecette', getrecette, name="getrecette"),
    path('gettiers', gettiers, name="gettiers"),
    path('boncommandemodi', boncommandemodi, name="boncommandemodi"),
    path('getprixemballage', getprixemballage, name="getprixemballage"),
    path('modiproduitvalid', modiproduitvalid, name="modiproduitvalid"),
    path('getpromodifier', getpromodifier, name="getpromodifier"),
    path('rapportlistepriseinventaire', rapportlistepriseinventaire, name="rapportlistepriseinventaire"),

    path('produit', produit, name="produit"),
    path('numerorectempodel', numerorectempodel, name="numerorectempodel"),
    path('getqte', getqte, name="getqte"),
    path('saveqte', saveqte, name="saveqte"),
    path('ajoutfournisseur', ajoutfournisseur, name="ajoutfournisseur"),
    path('uncheck', uncheck, name="uncheck"),
    path('rapclientco', rapclientco, name="rapclientco"),
    path('ImportExcel', ImportExcel, name="ImportExcel"),
    path('reimprimer', reimprimer, name='reimprimer'),
    path('annulation', annulation, name='annulation'),
    path('pointvente', pointvente, name='pointvente'),
    path('pointventeentree', pointventeentree, name='pointventeentree'),
    path('synthesepointvente', synthesepointvente, name='synthesepointvente'),
    # path('datamodal',datamodal,name='datamodal')

    path('etatbesoin2',etatbesoinn2,name='etatbesoin2'),
    path('etatbesoin',etatbesoinn,name='etatbesoin'),
    path('fac',fac,name='fac'),
    path('getstock',getstock,name='getstock'),
    path('modistock',modistock,name='modistock'),

    path('produitchange', produitchange,name='produitchange'),
    path('getproduitchangelocation', getproduitchangelocation,name='getproduitchangelocation'),
]
